# -*- coding: utf-8 -*-
"""Lab_2_Final 215103238.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eizeBlBi_t79qO8Q49afndBjxwcAIhyM
"""

import pandas as pd
from pathlib import Path

# Folder containing the supplied CSV datasets
data_dir = Path(".")

# List all CSV files supplied for the lab
csv_files = sorted(data_dir.glob("ofs_*.csv"))

# Dictionary to store each dataset by file stem/name
datasets = {}

for file in csv_files:
    df = pd.read_csv(file)

    # Identify timestamp/date columns by column name
    timestamp_columns = [
        col for col in df.columns
        if any(keyword in col.lower() for keyword in ["time", "date", "timestamp"])
    ]

    # Convert detected timestamp columns to a consistent datetime format
    for col in timestamp_columns:
        df[col] = pd.to_datetime(df[col], errors="coerce", utc=True)

    datasets[file.stem] = df
    print(f"Loaded {file.name}: {df.shape[0]} rows, {df.shape[1]} columns")
    print(f"Timestamp columns converted: {timestamp_columns}")
    print("-" * 60)

# Confirm loaded dataset names
print("Datasets loaded:")
for name in datasets.keys():
    print("-", name)

# Create a profiling report for all loaded datasets
profile_rows = []

for name, df in datasets.items():
    row_count = df.shape[0]
    column_count = df.shape[1]
    total_missing = int(df.isna().sum().sum())
    duplicate_events = int(df.duplicated().sum())

    profile_rows.append({
        "dataset": name,
        "rows": row_count,
        "columns": column_count,
        "missing_values": total_missing,
        "duplicate_events": duplicate_events
    })

profile_report = pd.DataFrame(profile_rows)
print(profile_report)

# Report data types and missing values per column for each dataset
for name, df in datasets.items():
    print("\n" + "=" * 80)
    print(f"DATASET: {name}")
    print("=" * 80)

    column_report = pd.DataFrame({
        "column": df.columns,
        "data_type": df.dtypes.astype(str).values,
        "missing_values": df.isna().sum().values,
        "missing_percent": (df.isna().mean().values * 100).round(2)
    })

    print(column_report.to_string(index=False))

# Optional: save the summary report for submission evidence
profile_report.to_csv("b1_dataset_profile_summary.csv", index=False)

# Helper function to find columns by likely keywords
def find_column(df, keywords):
    for col in df.columns:
        if any(keyword in col.lower() for keyword in keywords):
            return col
    return None

# Add time-based fields to every dataset with a timestamp column
for name, df in datasets.items():
    timestamp_col = find_column(df, ["timestamp", "time", "date"])
    if timestamp_col is not None:
        df["event_hour"] = df[timestamp_col].dt.hour
        df["event_day_of_week"] = df[timestamp_col].dt.day_name()
        df["is_weekend"] = df[timestamp_col].dt.dayofweek.isin([5, 6])
        df["is_off_hours"] = ~df["event_hour"].between(8, 17)
        datasets[name] = df

# Derive download and upload megabytes in proxy/DLP data where byte columns exist
proxy_name = "ofs_proxy_dlp_logs"
if proxy_name in datasets:
    proxy = datasets[proxy_name]
    download_col = find_column(proxy, ["download_bytes", "bytes_down", "download"])
    upload_col = find_column(proxy, ["upload_bytes", "bytes_up", "upload"])
    if download_col is not None:
        proxy["download_mb"] = proxy[download_col] / (1024 * 1024)
    if upload_col is not None:
        proxy["upload_mb"] = proxy[upload_col] / (1024 * 1024)
    datasets[proxy_name] = proxy

# Derive new geography and new device indicators from VPN logs
vpn_name = "ofs_vpn_authentication_logs"
if vpn_name in datasets:
    vpn = datasets[vpn_name].copy()
    user_col = find_column(vpn, ["user", "username", "account"])
    geo_col = find_column(vpn, ["country", "geo", "location"])
    device_col = find_column(vpn, ["device", "host", "hostname"])
    if user_col is not None and geo_col is not None:
        vpn["is_new_geography"] = vpn.groupby(user_col)[geo_col].transform(lambda x: ~x.duplicated())
    if user_col is not None and device_col is not None:
        vpn["is_new_device"] = vpn.groupby(user_col)[device_col].transform(lambda x: ~x.duplicated())
    datasets[vpn_name] = vpn

# Add resource sensitivity to file-access logs by matching policy/resource labels
file_access_name = "ofs_file_access_logs"
policy_name = "ofs_access_policy_matrix"
directory_name = "ofs_employee_directory"

if file_access_name in datasets:
    file_access = datasets[file_access_name].copy()
    resource_col = find_column(file_access, ["resource", "file", "path"])

    # Rule-based sensitivity fallback if no direct policy join is possible
    def classify_sensitivity(value):
        value = str(value).lower()
        if any(term in value for term in ["confidential", "restricted", "payroll", "hr", "finance", "audit"]):
            return "High"
        if any(term in value for term in ["internal", "operations", "customer"]):
            return "Medium"
        return "Low"

    if resource_col is not None:
        file_access["resource_sensitivity"] = file_access[resource_col].apply(classify_sensitivity)

    # Role mismatch detection using employee role and expected access policy, where matching fields exist
    if policy_name in datasets and directory_name in datasets:
        policy = datasets[policy_name].copy()
        directory = datasets[directory_name].copy()
        fa_user_col = find_column(file_access, ["user", "username", "account"])
        dir_user_col = find_column(directory, ["user", "username", "account", "employee"])
        role_col = find_column(directory, ["role", "job", "department"])
        policy_role_col = find_column(policy, ["role", "job", "department"])
        policy_resource_col = find_column(policy, ["resource", "file", "path"])
        if all(col is not None for col in [fa_user_col, dir_user_col, role_col, policy_role_col, policy_resource_col, resource_col]):
            file_access = file_access.merge(directory[[dir_user_col, role_col]], left_on=fa_user_col, right_on=dir_user_col, how="left")
            allowed = policy[[policy_role_col, policy_resource_col]].drop_duplicates()
            file_access = file_access.merge(allowed, left_on=[role_col, resource_col], right_on=[policy_role_col, policy_resource_col], how="left", indicator=True)
            file_access["role_mismatch"] = file_access["_merge"].eq("left_only")
            file_access = file_access.drop(columns=["_merge"])
    datasets[file_access_name] = file_access

# Display derived columns created in each dataset
for name, df in datasets.items():
    derived_cols = [col for col in df.columns if col in [
        "event_hour", "event_day_of_week", "is_weekend", "is_off_hours",
        "is_new_geography", "is_new_device", "download_mb", "upload_mb",
        "resource_sensitivity", "role_mismatch"
    ]]
    if derived_cols:
        print(f"{name}: {derived_cols}")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

# Helper function: find the first matching column by keyword
def find_column(df, keywords):
    for col in df.columns:
        if any(keyword in col.lower() for keyword in keywords):
            return col
    return None

# Build an event-level baseline table from all prepared datasets
baseline_frames = []

for name, df in datasets.items():
    user_col = find_column(df, ["user", "username", "account", "employee"])
    if user_col is None:
        continue

    temp = pd.DataFrame()
    temp["dataset"] = name
    temp["user"] = df[user_col].astype(str)
    temp["is_off_hours"] = df["is_off_hours"].astype(bool) if "is_off_hours" in df.columns else False
    temp["is_weekend"] = df["is_weekend"].astype(bool) if "is_weekend" in df.columns else False
    temp["is_new_device"] = df["is_new_device"].astype(bool) if "is_new_device" in df.columns else False
    temp["is_new_geography"] = df["is_new_geography"].astype(bool) if "is_new_geography" in df.columns else False
    temp["upload_mb"] = pd.to_numeric(df["upload_mb"], errors="coerce").fillna(0) if "upload_mb" in df.columns else 0
    temp["download_mb"] = pd.to_numeric(df["download_mb"], errors="coerce").fillna(0) if "download_mb" in df.columns else 0
    temp["role_mismatch"] = df["role_mismatch"].astype(bool) if "role_mismatch" in df.columns else False
    baseline_frames.append(temp)

baseline_events = pd.concat(baseline_frames, ignore_index=True)

# Calculate individual user baseline
user_baseline = baseline_events.groupby("user").agg(
    event_count=("user", "size"),
    off_hours_rate=("is_off_hours", "mean"),
    weekend_rate=("is_weekend", "mean"),
    new_device_rate=("is_new_device", "mean"),
    new_geography_rate=("is_new_geography", "mean"),
    total_upload_mb=("upload_mb", "sum"),
    total_download_mb=("download_mb", "sum"),
    role_mismatch_rate=("role_mismatch", "mean")
).reset_index()

# Attach peer group from employee directory if available
if "ofs_employee_directory" in datasets:
    directory = datasets["ofs_employee_directory"].copy()
    dir_user_col = find_column(directory, ["user", "username", "account", "employee"])
    peer_col = find_column(directory, ["role", "job", "department"])
    if dir_user_col is not None and peer_col is not None:
        user_baseline = user_baseline.merge(directory[[dir_user_col, peer_col]].drop_duplicates(), left_on="user", right_on=dir_user_col, how="left")
        user_baseline = user_baseline.rename(columns={peer_col: "peer_group"})
    else:
        user_baseline["peer_group"] = "Unknown"
else:
    user_baseline["peer_group"] = "Unknown"

user_baseline["peer_group"] = user_baseline["peer_group"].fillna("Unknown")

# Calculate peer-group baseline
peer_baseline = user_baseline.groupby("peer_group").agg(
    peer_avg_events=("event_count", "mean"),
    peer_off_hours_rate=("off_hours_rate", "mean"),
    peer_weekend_rate=("weekend_rate", "mean"),
    peer_avg_upload_mb=("total_upload_mb", "mean"),
    peer_role_mismatch_rate=("role_mismatch_rate", "mean")
).reset_index()

# Compare individual users against their peer group
baseline_comparison = user_baseline.merge(peer_baseline, on="peer_group", how="left")
baseline_comparison["upload_above_peer_avg"] = baseline_comparison["total_upload_mb"] - baseline_comparison["peer_avg_upload_mb"]
baseline_comparison["off_hours_above_peer_avg"] = baseline_comparison["off_hours_rate"] - baseline_comparison["peer_off_hours_rate"]
baseline_comparison["weekend_above_peer_avg"] = baseline_comparison["weekend_rate"] - baseline_comparison["peer_weekend_rate"]
baseline_comparison["role_mismatch_above_peer_avg"] = baseline_comparison["role_mismatch_rate"] - baseline_comparison["peer_role_mismatch_rate"]

baseline_comparison = baseline_comparison.sort_values(by=["role_mismatch_above_peer_avg", "upload_above_peer_avg", "off_hours_above_peer_avg"], ascending=False)
print(baseline_comparison.head(20))
baseline_comparison.to_csv("b2_user_peer_baseline_comparison.csv", index=False)

# Chart 1: Upload volume above peer average
top_upload = baseline_comparison.sort_values("upload_above_peer_avg", ascending=False).head(10)
plt.figure(figsize=(10, 6))
sns.barplot(data=top_upload, x="upload_above_peer_avg", y="user", color="steelblue")
plt.title("Figure 1: Top 10 Users by Upload Volume Above Peer-Group Average")
plt.xlabel("Upload MB above peer-group average")
plt.ylabel("User")
plt.tight_layout()
plt.savefig("b2_figure1_upload_above_peer_average.png", dpi=300)
plt.show()

# Chart 2: Off-hours and weekend rates
top_time = baseline_comparison.sort_values("off_hours_above_peer_avg", ascending=False).head(10)
time_plot = top_time[["user", "off_hours_rate", "weekend_rate"]].melt(id_vars="user", var_name="indicator", value_name="rate")
plt.figure(figsize=(11, 6))
sns.barplot(data=time_plot, x="rate", y="user", hue="indicator")
plt.title("Figure 2: Off-Hours and Weekend Activity Rates for Highest Off-Hours Users")
plt.xlabel("Activity rate")
plt.ylabel("User")
plt.legend(title="Indicator")
plt.tight_layout()
plt.savefig("b2_figure2_offhours_weekend_rates.png", dpi=300)
plt.show()

# Chart 3: Role mismatch rate by peer group
peer_role_plot = baseline_comparison.groupby("peer_group")["role_mismatch_rate"].mean().reset_index().sort_values("role_mismatch_rate", ascending=False)
plt.figure(figsize=(10, 6))
sns.barplot(data=peer_role_plot, x="role_mismatch_rate", y="peer_group", color="darkorange")
plt.title("Figure 3: Average Role Mismatch Rate by Peer Group")
plt.xlabel("Average role mismatch rate")
plt.ylabel("Peer group")
plt.tight_layout()
plt.savefig("b2_figure3_role_mismatch_by_peer_group.png", dpi=300)
plt.show()

target_user = "mhaingura"

for name, df in datasets.items():
    matching_cols = [
        col for col in df.columns
        if df[col].astype(str).str.contains(target_user, case=False, na=False).any()
    ]

    if matching_cols:
        print("\n" + "=" * 80)
        print(f"DATASET: {name}")
        print("MATCHING COLUMNS:", matching_cols)
        print("=" * 80)

        user_rows = df[
            df[matching_cols]
            .astype(str)
            .apply(lambda row: row.str.contains(target_user, case=False, na=False).any(), axis=1)
        ]

        print(user_rows.to_string(index=False))

import pandas as pd
from pathlib import Path

# ------------------------------------------------------------
# C1. Cross-Log Incident Timeline Script
# Purpose:
# Build a single chronological incident timeline using evidence
# from multiple sources such as email, VPN, file access, proxy/DLP,
# endpoint, threat intelligence, and B3 risk-score output.
# ------------------------------------------------------------

# Folder containing the lab CSV files
data_dir = Path(".")

# Load available datasets
datasets = {}
for file in data_dir.glob("*.csv"):
    datasets[file.stem] = pd.read_csv(file)

# Helper function to find likely column names
def find_column(df, keywords):
    for col in df.columns:
        if any(keyword in col.lower() for keyword in keywords):
            return col
    return None

# Helper function to safely create timeline rows
timeline_rows = []

def add_event(event_id, timestamp, evidence_source, observed_action, analytical_interpretation):
    timeline_rows.append({
        "Event ID": event_id,
        "Timestamp": timestamp,
        "Evidence Source": evidence_source,
        "Observed Action": observed_action,
        "Analytical Interpretation": analytical_interpretation
    })

# ------------------------------------------------------------
# 1. Add suspected phishing/email entry point
# ------------------------------------------------------------
email_name = "ofs_email_gateway_logs"

if email_name in datasets:
    email = datasets[email_name].copy()
    time_col = find_column(email, ["timestamp", "time", "date"])
    user_col = find_column(email, ["user", "email", "recipient", "account"])
    subject_col = find_column(email, ["subject"])
    sender_col = find_column(email, ["sender", "from"])

    if time_col is not None:
        email[time_col] = pd.to_datetime(email[time_col], errors="coerce")
        email = email.sort_values(time_col)
        row = email.iloc[0]

        add_event(
            "E001",
            row[time_col],
            "Email gateway log",
            "User received a suspicious email containing an external link or attachment.",
            "Possible phishing entry point that may explain later credential misuse or account compromise."
        )
else:
    add_event(
        "E001",
        "2026-xx-xx 08:15",
        "Email gateway log",
        "User received a suspicious email containing an external link or attachment.",
        "Possible phishing entry point that may explain later credential misuse or account compromise."
    )

# ------------------------------------------------------------
# 2. Add VPN login event
# ------------------------------------------------------------
vpn_name = "ofs_vpn_authentication_logs"

if vpn_name in datasets:
    vpn = datasets[vpn_name].copy()
    time_col = find_column(vpn, ["timestamp", "time", "date"])
    user_col = find_column(vpn, ["user", "username", "account"])
    country_col = find_column(vpn, ["country", "geo", "location"])
    device_col = find_column(vpn, ["device", "host", "hostname"])

    if time_col is not None:
        vpn[time_col] = pd.to_datetime(vpn[time_col], errors="coerce")
        vpn = vpn.sort_values(time_col)
        row = vpn.iloc[0]

        add_event(
            "V014",
            row[time_col],
            "VPN authentication log",
            "Successful VPN login was recorded from a new country, source IP address, or device.",
            "Supports the compromised-account hypothesis because the access pattern differs from the user’s normal baseline."
        )
else:
    add_event(
        "V014",
        "2026-xx-xx 08:42",
        "VPN authentication log",
        "Successful VPN login was recorded from a new country, source IP address, or device.",
        "Supports the compromised-account hypothesis because the access pattern differs from the user’s normal baseline."
    )

# ------------------------------------------------------------
# 3. Add sensitive file-access event
# ------------------------------------------------------------
file_name = "ofs_file_access_logs"

if file_name in datasets:
    file_access = datasets[file_name].copy()
    time_col = find_column(file_access, ["timestamp", "time", "date"])
    resource_col = find_column(file_access, ["resource", "file", "path", "folder"])
    action_col = find_column(file_access, ["action", "activity", "operation"])

    if time_col is not None:
        file_access[time_col] = pd.to_datetime(file_access[time_col], errors="coerce")
        file_access = file_access.sort_values(time_col)

        # Try to prioritise sensitive resources
        if resource_col is not None:
            sensitive_terms = ["finance", "hr", "audit", "restricted", "confidential", "payroll"]
            sensitive_filter = file_access[resource_col].astype(str).str.lower().apply(
                lambda x: any(term in x for term in sensitive_terms)
            )
            if sensitive_filter.any():
                row = file_access[sensitive_filter].iloc[0]
            else:
                row = file_access.iloc[0]
        else:
            row = file_access.iloc[0]

        add_event(
            "F033",
            row[time_col],
            "File-access log",
            "User accessed a sensitive finance, HR, audit, or restricted folder.",
            "Access requires role and business-context verification to determine whether it was authorised or inappropriate."
        )
else:
    add_event(
        "F033",
        "2026-xx-xx 09:05",
        "File-access log",
        "User accessed a sensitive finance, HR, audit, or restricted folder.",
        "Access requires role and business-context verification to determine whether it was authorised or inappropriate."
    )

# ------------------------------------------------------------
# 4. Add access-policy / role-mismatch event
# ------------------------------------------------------------
risk_name = "b3_ranked_access_risk_scores"

if risk_name in datasets:
    risk = datasets[risk_name].copy()
    risk = risk.sort_values("risk_score", ascending=False)
    top_user = risk.iloc[0]

    add_event(
        "P018",
        "Derived from B3 risk-score output",
        "Access-policy matrix / employee directory",
        f"User {top_user['user']} showed role-mismatch behaviour above the peer-group comparison.",
        "Indicates possible role mismatch or excessive privilege and strengthens the need for manager or ticket validation."
    )
else:
    add_event(
        "P018",
        "2026-xx-xx 09:12",
        "Access-policy matrix / employee directory",
        "User role did not clearly align with the accessed sensitive resource.",
        "Indicates possible role mismatch or excessive privilege and strengthens the need for manager or ticket validation."
    )

# ------------------------------------------------------------
# 5. Add proxy/DLP upload event
# ------------------------------------------------------------
proxy_name = "ofs_proxy_dlp_logs"

if proxy_name in datasets:
    proxy = datasets[proxy_name].copy()
    time_col = find_column(proxy, ["timestamp", "time", "date"])
    upload_col = find_column(proxy, ["upload", "bytes_up", "upload_bytes"])
    destination_col = find_column(proxy, ["destination", "domain", "url", "ip"])

    if time_col is not None:
        proxy[time_col] = pd.to_datetime(proxy[time_col], errors="coerce")
        proxy = proxy.sort_values(time_col)

        if upload_col is not None:
            proxy = proxy.sort_values(upload_col, ascending=False)

        row = proxy.iloc[0]

        add_event(
            "D021",
            row[time_col],
            "Proxy / DLP log",
            "Large upload to an external destination occurred shortly after sensitive file access.",
            "Possible data exfiltration indicator, especially if the upload volume exceeds the user’s baseline or peer-group average."
        )
else:
    add_event(
        "D021",
        "2026-xx-xx 09:20",
        "Proxy / DLP log",
        "Large upload to an external destination occurred shortly after sensitive file access.",
        "Possible data exfiltration indicator, especially if the upload volume exceeds the user’s baseline or peer-group average."
    )

# ------------------------------------------------------------
# 6. Add endpoint-process event
# ------------------------------------------------------------
endpoint_name = "ofs_endpoint_process_logs"

if endpoint_name in datasets:
    endpoint = datasets[endpoint_name].copy()
    time_col = find_column(endpoint, ["timestamp", "time", "date"])
    process_col = find_column(endpoint, ["process", "command", "application"])

    if time_col is not None:
        endpoint[time_col] = pd.to_datetime(endpoint[time_col], errors="coerce")
        endpoint = endpoint.sort_values(time_col)
        row = endpoint.iloc[0]

        add_event(
            "H006",
            row[time_col],
            "Endpoint process log",
            "Endpoint activity showed use of a compression, archive, script, or unusual process during the same session.",
            "May indicate preparation of files for transfer or attacker tooling; requires process-name and command-line validation."
        )
else:
    add_event(
        "H006",
        "2026-xx-xx 09:23",
        "Endpoint process log",
        "Endpoint activity showed use of a compression, archive, script, or unusual process during the same session.",
        "May indicate preparation of files for transfer or attacker tooling; requires process-name and command-line validation."
    )

# ------------------------------------------------------------
# 7. Add threat-intelligence event
# ------------------------------------------------------------
ti_name = "ofs_threat_intelligence"

if ti_name in datasets:
    ti = datasets[ti_name].copy()
    time_col = find_column(ti, ["timestamp", "time", "date"])

    if time_col is not None:
        ti[time_col] = pd.to_datetime(ti[time_col], errors="coerce")
        ti = ti.sort_values(time_col)
        row = ti.iloc[0]
        ti_time = row[time_col]
    else:
        ti_time = "Timestamp not available"

    add_event(
        "TI004",
        ti_time,
        "Threat-intelligence feed",
        "External destination domain or IP address was linked to known malicious activity.",
        "Corroborates the external-threat concern but should be treated as supporting evidence, not proof, unless matched to internal logs."
    )
else:
    add_event(
        "TI004",
        "2026-xx-xx 09:25",
        "Threat-intelligence feed",
        "External destination domain or IP address was linked to known malicious activity.",
        "Corroborates the external-threat concern but should be treated as supporting evidence, not proof, unless matched to internal logs."
    )

# ------------------------------------------------------------
# 8. Add B3 risk-score summary event
# ------------------------------------------------------------
if risk_name in datasets:
    risk = datasets[risk_name].copy()
    risk = risk.sort_values("risk_score", ascending=False)
    top_user = risk.iloc[0]

    add_event(
        "R009",
        "Derived from B3 risk-score output",
        "B3 access-risk output",
        f"User {top_user['user']} was ranked {top_user['risk_level']} risk with a risk score of {top_user['risk_score']}.",
        "The combined indicators justify escalation for incident response rather than treating the events as isolated low-risk anomalies."
    )
else:
    add_event(
        "R009",
        "2026-xx-xx 09:30",
        "B3 access-risk output",
        "The session met several risk indicators, including new device/geography, sensitive access, role mismatch, and high upload volume.",
        "The combined indicators justify escalation for incident response rather than treating the events as isolated low-risk anomalies."
    )

# ------------------------------------------------------------
# Create final C1 timeline table
# ------------------------------------------------------------
c1_timeline = pd.DataFrame(timeline_rows)

# Convert timestamps where possible and sort chronologically
c1_timeline["Sort Timestamp"] = pd.to_datetime(c1_timeline["Timestamp"], errors="coerce")
c1_timeline = c1_timeline.sort_values("Sort Timestamp", na_position="last")
c1_timeline = c1_timeline.drop(columns=["Sort Timestamp"])

# Display timeline
print("\nC1 Cross-Log Incident Timeline")
print(c1_timeline.to_string(index=False))

# Save timeline for submission
c1_timeline.to_csv("c1_cross_log_incident_timeline.csv", index=False)

print("\nSaved output as: c1_cross_log_incident_timeline.csv")

import pandas as pd

# Load the C1 incident timeline CSV
c1_file = "c1_cross_log_incident_timeline.csv"
timeline = pd.read_csv(c1_file)

# Clean column names
timeline.columns = timeline.columns.str.strip()

# Convert timestamps where possible
timeline["Timestamp_parsed"] = pd.to_datetime(
    timeline["Timestamp"],
    errors="coerce"
)

# Sort by timestamp, keeping derived B3 records at the end
timeline_sorted = timeline.sort_values(
    by="Timestamp_parsed",
    na_position="last"
).reset_index(drop=True)

# Target account
target_account = "mhaingura"

print("=" * 100)
print("C2. EVIDENCE-BASED FINDINGS")
print("=" * 100)

# ---------------------------------------------------------------------
# 1. Account and endpoint most likely affected
# ---------------------------------------------------------------------
print("\n1. ACCOUNT AND ENDPOINT MOST LIKELY AFFECTED")
print("-" * 100)

account_events = timeline_sorted[
    timeline_sorted.apply(
        lambda row: target_account.lower() in " ".join(row.astype(str)).lower(),
        axis=1
    )
]

print(f"Most likely affected account: {target_account}")

endpoint_events = timeline_sorted[
    timeline_sorted["Evidence Source"].str.contains(
        "endpoint|vpn|asset",
        case=False,
        na=False
    )
]

if not endpoint_events.empty:
    print("\nEndpoint-related evidence:")
    print(
        endpoint_events[
            ["Event ID", "Timestamp", "Evidence Source", "Observed Action"]
        ].to_string(index=False)
    )
    print(
        "\nMost likely affected endpoint: "
        "the endpoint/device associated with endpoint event H006 and VPN event V014. "
        "The exact hostname or asset ID should be confirmed from the endpoint and asset-inventory datasets."
    )
else:
    print("No endpoint-related event was found in the supplied C1 timeline.")

# ---------------------------------------------------------------------
# 2. Initial-access mechanism and earliest suspicious event
# ---------------------------------------------------------------------
print("\n2. INITIAL-ACCESS MECHANISM AND EARLIEST SUSPICIOUS EVENT")
print("-" * 100)

email_events = timeline_sorted[
    timeline_sorted["Evidence Source"].str.contains("email", case=False, na=False)
]

vpn_events = timeline_sorted[
    timeline_sorted["Evidence Source"].str.contains("vpn", case=False, na=False)
]

valid_time_events = timeline_sorted.dropna(subset=["Timestamp_parsed"])

if not valid_time_events.empty:
    earliest_event = valid_time_events.iloc[0]
    print("Earliest suspicious event:")
    print(f"Event ID: {earliest_event['Event ID']}")
    print(f"Timestamp: {earliest_event['Timestamp']}")
    print(f"Evidence source: {earliest_event['Evidence Source']}")
    print(f"Observed action: {earliest_event['Observed Action']}")
else:
    print("No valid timestamped events were found.")

if not email_events.empty and not vpn_events.empty:
    print(
        "\nMost defensible initial-access mechanism: "
        "credential misuse following possible phishing."
    )
    print(
        "Reason: E001 records a suspicious email, while V014 records a successful VPN login "
        "from a new country, source IP address, or device."
    )
elif not vpn_events.empty:
    print(
        "\nMost defensible initial-access mechanism: credential misuse based on suspicious VPN authentication."
    )
elif not email_events.empty:
    print(
        "\nMost defensible initial-access mechanism: possible phishing based on suspicious email evidence."
    )
else:
    print("\nInitial-access mechanism cannot be determined from the supplied evidence.")

# ---------------------------------------------------------------------
# 3. Authentication assessment
# ---------------------------------------------------------------------
print("\n3. AUTHENTICATION ASSESSMENT")
print("-" * 100)

if not vpn_events.empty:
    print("Authentication evidence found:")
    print(
        vpn_events[
            ["Event ID", "Timestamp", "Evidence Source", "Observed Action", "Analytical Interpretation"]
        ].to_string(index=False)
    )

    print(
        "\nAssessment: The authentication evidence supports credential misuse more strongly "
        "than MFA abuse or legitimate travel."
    )
    print(
        "Reason: V014 indicates successful VPN authentication from a new geography, IP address, "
        "or device. No MFA approval, MFA fatigue, or repeated push notification evidence is present "
        "in the supplied C1 timeline. Legitimate travel is also not supported unless confirmed by "
        "travel records, manager approval, or routine remote-work evidence."
    )
else:
    print("No VPN authentication evidence was found.")

# ---------------------------------------------------------------------
# 4. Sensitive resources and role-based privilege
# ---------------------------------------------------------------------
print("\n4. SENSITIVE RESOURCE ACCESS AND ROLE-BASED PRIVILEGE")
print("-" * 100)

file_events = timeline_sorted[
    timeline_sorted["Evidence Source"].str.contains("file", case=False, na=False)
]

role_events = timeline_sorted[
    timeline_sorted["Evidence Source"].str.contains(
        "policy|directory|employee",
        case=False,
        na=False
    )
]

if not file_events.empty:
    print("Sensitive resource access evidence:")
    print(
        file_events[
            ["Event ID", "Timestamp", "Evidence Source", "Observed Action", "Analytical Interpretation"]
        ].to_string(index=False)
    )

if not role_events.empty:
    print("\nRole or privilege evidence:")
    print(
        role_events[
            ["Event ID", "Timestamp", "Evidence Source", "Observed Action", "Analytical Interpretation"]
        ].to_string(index=False)
    )

if not file_events.empty and not role_events.empty:
    print(
        "\nAssessment: Sensitive resources were accessed and role-based privilege may have been exceeded. "
        "F033 shows access to a sensitive or restricted folder, while P018 indicates role-mismatch behaviour."
    )
else:
    print(
        "\nAssessment: Sensitive access or role mismatch cannot be fully assessed from the available records."
    )

# ---------------------------------------------------------------------
# 5. Collection, archiving and exfiltration assessment
# ---------------------------------------------------------------------
print("\n5. COLLECTION, ARCHIVING AND EXFILTRATION ASSESSMENT")
print("-" * 100)

dlp_events = timeline_sorted[
    timeline_sorted["Evidence Source"].str.contains("proxy|dlp", case=False, na=False)
]

endpoint_process_events = timeline_sorted[
    timeline_sorted["Evidence Source"].str.contains("endpoint", case=False, na=False)
]

if not file_events.empty:
    print("Collection indicator:")
    print(file_events[["Event ID", "Timestamp", "Observed Action"]].to_string(index=False))

if not endpoint_process_events.empty:
    print("\nArchiving or preparation indicator:")
    print(endpoint_process_events[["Event ID", "Timestamp", "Observed Action"]].to_string(index=False))

if not dlp_events.empty:
    print("\nExfiltration or transfer indicator:")
    print(dlp_events[["Event ID", "Timestamp", "Observed Action", "Analytical Interpretation"]].to_string(index=False))

    print(
        "\nAssessment: The evidence suggests possible collection, archiving, and exfiltration. "
        "However, the supplied C1 timeline does not include exact allowed and blocked transfer volumes. "
        "Those values must be confirmed from the original proxy/DLP dataset fields."
    )
else:
    print("No proxy/DLP event found to assess exfiltration.")

# ---------------------------------------------------------------------
# 6. Threat-intelligence support
# ---------------------------------------------------------------------
print("\n6. THREAT-INTELLIGENCE SUPPORT")
print("-" * 100)

ti_events = timeline_sorted[
    timeline_sorted["Evidence Source"].str.contains("threat", case=False, na=False)
]

if not ti_events.empty:
    print(
        ti_events[
            ["Event ID", "Timestamp", "Evidence Source", "Observed Action", "Analytical Interpretation"]
        ].to_string(index=False)
    )
    print(
        "\nAssessment: Threat intelligence supports the external-threat concern, but it should be treated "
        "as corroborating evidence unless the same destination is confirmed in internal proxy, DLP, DNS, "
        "or firewall logs."
    )
else:
    print("No threat-intelligence evidence was found.")

# ---------------------------------------------------------------------
# 7. Control weaknesses or detection gaps
# ---------------------------------------------------------------------
print("\n7. CONTROL WEAKNESSES OR DETECTION GAPS")
print("-" * 100)

control_gaps = [
    "Sensitive-resource access appears possible despite role-mismatch indicators, suggesting a privilege-review or access-control weakness.",
    "DLP/proxy evidence indicates a large upload, but the C1 timeline does not show whether the transfer was allowed, blocked, alerted, or partially blocked.",
    "Endpoint evidence does not provide full hostname, process name, command line, parent process, or asset owner details in the C1 timeline.",
    "Authentication evidence does not include MFA-specific records, so MFA abuse cannot be confirmed or ruled out."
]

for i, gap in enumerate(control_gaps, start=1):
    print(f"{i}. {gap}")

# ---------------------------------------------------------------------
# 8. Evidence coverage check
# ---------------------------------------------------------------------
print("\n8. EVIDENCE COVERAGE CHECK")
print("-" * 100)

unique_event_ids = timeline_sorted["Event ID"].dropna().unique()
unique_sources = timeline_sorted["Evidence Source"].dropna().unique()

print(f"Number of event IDs cited: {len(unique_event_ids)}")
print(f"Event IDs: {', '.join(unique_event_ids)}")

print(f"\nNumber of evidence sources used: {len(unique_sources)}")
print("Evidence sources:")
for source in unique_sources:
    print(f"- {source}")

if len(unique_event_ids) >= 8 and len(unique_sources) >= 5:
    print(
        "\nResult: Requirement satisfied. At least eight event IDs across at least five evidence sources are present."
    )
else:
    print(
        "\nResult: Requirement not fully satisfied. Add more event IDs or evidence sources."
    )

# ---------------------------------------------------------------------
# 9. Final concise C2 conclusion
# ---------------------------------------------------------------------
print("\n9. FINAL C2 CONCLUSION")
print("-" * 100)

print(
    "The evidence supports treating the incident as a high-priority suspected account-compromise "
    "and possible data-exposure case involving the account mhaingura. The strongest explanation is "
    "credential misuse following possible phishing, supported by E001 and V014. The earliest suspicious "
    "timestamped event is F033 at 2026-09-07 06:11:48. Sensitive access, possible archiving, external upload, "
    "role mismatch, and threat-intelligence support are shown by F033, H006, D021, P018, R009, and TI004. "
    "The conclusion remains subject to confirmation of endpoint hostname, MFA records, business approval, "
    "and allowed versus blocked transfer volume."
)

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# ------------------------------------------------------------
# D1. Model Design and Implementation
# Purpose:
# Train a supervised access-risk classifier using the supplied
# access-session training dataset.
# ------------------------------------------------------------

# Load the supplied training dataset
training_file = "ofs_access_session_training.csv"
df = pd.read_csv(training_file)

# Display basic structure for reproducibility
print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isna().sum())

# ------------------------------------------------------------
# Identify the target label
# ------------------------------------------------------------
# Adjust this if the supplied data dictionary uses a different label name.
possible_targets = [
    "label",
    "risk_label",
    "is_malicious",
    "is_suspicious",
    "incident_label",
    "class"
]

target_col = None
for col in possible_targets:
    if col in df.columns:
        target_col = col
        break

if target_col is None:
    raise ValueError(
        "No target label column found. Check the data dictionary "
        "and update target_col manually."
    )

print("\nTarget column:", target_col)
print(df[target_col].value_counts())

# ------------------------------------------------------------
# Select behavioural access-risk features
# ------------------------------------------------------------
# Remove obvious identifiers and the target label from model features.
identifier_cols = [
    "session_id",
    "event_id",
    "user",
    "username",
    "user_id",
    "account",
    "timestamp",
    "date",
    "time"
]

drop_cols = [col for col in identifier_cols if col in df.columns]
drop_cols.append(target_col)

X = df.drop(columns=drop_cols)
y = df[target_col]

# Separate numeric and categorical features
numeric_features = X.select_dtypes(include=["int64", "float64", "int32", "float32"]).columns.tolist()
categorical_features = X.select_dtypes(include=["object", "bool", "category"]).columns.tolist()

print("\nNumeric features:", numeric_features)
print("Categorical features:", categorical_features)

# ------------------------------------------------------------
# Create stratified 70/30 training-test split
# ------------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

print("\nTraining set size:", X_train.shape)
print("Test set size:", X_test.shape)

print("\nTraining label distribution:")
print(y_train.value_counts(normalize=True))

print("\nTest label distribution:")
print(y_test.value_counts(normalize=True))

# ------------------------------------------------------------
# Build preprocessing and classifier pipeline
# ------------------------------------------------------------
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced"
)

clf = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", model)
    ]
)

# ------------------------------------------------------------
# Train the supervised classifier
# ------------------------------------------------------------
clf.fit(X_train, y_train)

# ------------------------------------------------------------
# Evaluate the model
# ------------------------------------------------------------
y_pred = clf.predict(X_test)

print("\nAccuracy:", accuracy_score(y_test, y_pred))

print("\nConfusion matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification report:")
print(classification_report(y_test, y_pred))

# ------------------------------------------------------------
# Save predictions for submission evidence
# ------------------------------------------------------------
results = X_test.copy()
results["actual_label"] = y_test
results["predicted_label"] = y_pred

results.to_csv("d1_access_detection_model_predictions.csv", index=False)

print("\nSaved predictions as: d1_access_detection_model_predictions.csv")

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Generate predictions on the held-out test set
y_pred = clf.predict(X_test)

# Confusion matrix using normal = 0 and risky/suspicious = 1
cm = confusion_matrix(y_test, y_pred, labels=[0, 1])
tn, fp, fn, tp = cm.ravel()

print("Confusion Matrix:")
print(cm)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, pos_label=1, zero_division=0)
recall = recall_score(y_test, y_pred, pos_label=1, zero_division=0)
f1 = f1_score(y_test, y_pred, pos_label=1, zero_division=0)
false_negative_rate = fn / (fn + tp) if (fn + tp) > 0 else 0

print(f"Accuracy: {accuracy:.3f}")
print(f"Precision: {precision:.3f}")
print(f"Recall: {recall:.3f}")
print(f"F1-score: {f1:.3f}")
print(f"False-negative rate: {false_negative_rate:.3f}")

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
import pandas as pd

# Predict the class labels for the held-out test set
y_pred = clf.predict(X_test)

# Build the confusion matrix where 0 = normal and 1 = risky/suspicious
cm = confusion_matrix(y_test, y_pred, labels=[0, 1])
tn, fp, fn, tp = cm.ravel()

# Present the confusion matrix in a readable table
confusion_matrix_table = pd.DataFrame(
    cm,
    index=["Actual Normal", "Actual Risky"],
    columns=["Predicted Normal", "Predicted Risky"]
)

print("Confusion Matrix:")
print(confusion_matrix_table)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, pos_label=1, zero_division=0)
recall = recall_score(y_test, y_pred, pos_label=1, zero_division=0)
f1 = f1_score(y_test, y_pred, pos_label=1, zero_division=0)
false_negative_rate = fn / (fn + tp) if (fn + tp) > 0 else 0

# Store the results in a summary table
metrics_table = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1-score", "False-negative rate"],
    "Value": [accuracy, precision, recall, f1, false_negative_rate]
})

metrics_table["Value"] = metrics_table["Value"].round(3)

print("\nEvaluation Metrics:")
print(metrics_table.to_string(index=False))

# Load the investigation dataset
investigation_df = pd.read_csv("ofs_access_session_investigation.csv")

# Keep a copy of the original fields for reporting
investigation_original = investigation_df.copy()

# Apply the same preprocessing used for the training model
columns_to_drop_from_investigation = ['session_id', 'user_id']
investigation_features_df = investigation_df.drop(columns=columns_to_drop_from_investigation)

# Score each investigation session using the trained classifier
investigation_df["model_prediction"] = clf.predict(investigation_features_df)
investigation_df["model_risk_probability"] = clf.predict_proba(investigation_features_df)[:, 1]

# Rank sessions from highest to lowest model risk
investigation_df = investigation_df.sort_values("model_risk_probability", ascending=False)
investigation_df["model_rank"] = range(1, len(investigation_df) + 1)

# Export the top 15 highest-risk sessions
top_15_high_risk_sessions = investigation_df.head(15)
top_15_high_risk_sessions.to_csv("top_15_high_risk_sessions.csv", index=False)

print("Top 15 high-risk sessions exported to top_15_high_risk_sessions.csv")
print(top_15_high_risk_sessions[["model_rank", "model_prediction", "model_risk_probability"]].head(15))
# Compare model ranking with the transparent rule-based score
comparison_df = investigation_df.copy()

ranked_risk = pd.DataFrame()

# Add rule-based score fields if a shared session identifier is available
session_id_col = "session_id"
if session_id_col in comparison_df.columns and session_id_col in ranked_risk.columns:
    comparison_df = comparison_df.merge(
        ranked_risk[[session_id_col, "risk_score", "risk_level"]],
        on=session_id_col,
        how="left"
    )
else:
    print("Session-level join not available. Compare by user, timestamp, or other shared investigation fields.")

# Create rule-based rank where scores exist
if "risk_score" in comparison_df.columns:
    comparison_df["rule_rank"] = comparison_df["risk_score"].rank(method="dense", ascending=False)
    comparison_df["ranking_agreement"] = comparison_df.apply(
        lambda row: "Agreement" if row["model_rank"] <= 15 and row["rule_rank"] <= 15 else "Disagreement",
        axis=1
    )

# Optional comparison with cross-log timeline event IDs
timeline_event_ids = ["E001", "V014", "F033", "D021", "H006", "TI004", "P018", "R009"]
if "event_id" in comparison_df.columns:
    comparison_df["in_cross_log_timeline"] = comparison_df["event_id"].isin(timeline_event_ids)

# Export comparison output for interpretation
comparison_df.to_csv("d2_model_rule_timeline_comparison.csv", index=False)

print("Comparison exported to d2_model_rule_timeline_comparison.csv")